### ISSUE TITLE
Методы ElemArrayList.addAll( ... ) не соблюдают контракт конструктора aAllowDuplicates = false

### ISSUE THREAD

**Issue by mkovach** [toxsoft-org/ts4-core#3]
При добавлении элементов в список через методы ElemArrayList.addAll( ... ) в списке может оказаться один и тот же элемент несколько раз даже если при вызове конструктора ElemArrayList было указано aAllowDuplicates = false

**Comment by hazard157** [comment]
Устранено. Вроде без ошибок :)
